### ISSUE TITLE
Can you update the readme about how to reproduce results shown in the readme

### ISSUE THREAD

**Issue by aertist** [Beinabih/Pytorch-HeadTrip#1]
Awesome repo. 
I also made a colab notebook for this. (You can ad this to readme if you want)

I encountered several errors when I set `no_class: True` 

```
`Traceback (most recent call last):
  File "dream.py", line 470, in <module>
    start_dreamer(config)
  File "dream.py", line 451, in start_dreamer
    dreamer = Dreamer(img_p, outpath, config)
  File "dream.py", line 74, in __init__
    self.model = nn.Sequential(*self.layers[: (self.at_layer_para + 1)])
AttributeError: 'Dreamer' object has no attribute 'layers'`
```

And It is using the cached MiDAS data. Can you tell me how to use this depth function properly?

```
`Using cache found in depth_model/intel-isl_MiDaS_master
Loading weights:  None
Using cache found in depth_model/rwightman_gen-efficientnet-pytorch_master
Using cache found in depth_model/intel-isl_MiDaS_master`
```

[This](https://imgur.com/a/qdPHJwj) is what I made using the colab with `model: masnet` and `iterations: 10`

**Comment by Beinabih** [comment]
Hey, thank you.

I added the colab notebook to my readme.

I pushed a new version where it should work for vgg19 only since other models have a different internal layer structure. 
I will come up with a solution soon.

Its downloading the MiDas weights to a local folder called "depth_model" on the initial run. You need to change the parameters in the config file (there is an instruction in the article).

For the colab approach it should work when you define a dictionary like so:
```
from dream import start_dreamer
config = {}
config['num_iterations']= 8
config['num_octaves']= 40
config['octave_scale']= 1.2
config['lr']= 0.01
#and so on 
start_dreamer(config)
```

**Comment by aertist** [comment]
Hi, I tried to do create a dictionary in colab but its not working. 

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-32-cc6d623a68ae> in <module>()
     81 
     82 
---> 83 start_dreamer(config)

1 frames
/usr/lib/python3.7/genericpath.py in isdir(s)
     40     """Return true if the pathname refers to an existing directory."""
     41     try:
---> 42         st = os.stat(s)
     43     except OSError:
     44         return False

TypeError: stat: path should be string, bytes, os.PathLike or integer, not set

```

Can you suggest the necessary edits in the code?

**Comment by Beinabih** [comment]
Yeah, don't use brackets 

it should be 
`config['num_iterations']= num_iterations` 
not
`config['num_iterations']= {num_iterations}`

**Comment by aertist** [comment]
Now it is working when I set `seq: False` (i. e. only for single images)
But when I try to process a video it is out putting this error:

```
Using cache found in depth_model/intel-isl_MiDaS_master
Using cache found in depth_model/rwightman_gen-efficientnet-pytorch_master
Loading weights:  None
Using cache found in depth_model/intel-isl_MiDaS_master
15 1.3 10 0.008
Dreaming: 100%|██████████| 10/10 [00:11<00:00,  1.11s/it]
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-14-a2e28224c74b> in <module>()
     80 config['fp16']= fp16
     81 
---> 82 start_dreamer(config)

2 frames
/content/Pytorch-HeadTrip/dream.py in get_opflow_image(self, img1, dream_img, img2)
    324 
    325         h, w, c = img1.shape
--> 326         if config["use_spynet"]:
    327             flow = calc_opflow(np.uint8(img1), np.uint8(img2))
    328             flow = np.transpose(np.float32(flow), (1, 2, 0))

NameError: name 'config' is not defined
```
looks like the spynet optical flow is causing the issue? 👀
It works fine when I use the `--config` command and manually edit the `.yaml` file.

**Comment by Beinabih** [comment]
yea right, it should be `self.config` , i pushed a new version

**Comment by aertist** [comment]
Now its working properly. 💪
I wanted to ask, when are there any plans to add support of other architectures (models)? specifically the [MITPlaces](https://github.com/CSAILVision/places365) ? (365 and 205 both can be downloaded here for pytorch) 👀 
An example deep dreamed video using Places205 model can be seen [here.](https://www.youtube.com/watch?v=Ig9JbZxzoW4)

Also, Can we some how boost the speed of dreaming? It is taking almost a minute to process a 1920x1080 frame from a video on a NVIDIA Tesla T4 GPU.

Here is what I made with this so far:<blockquote class="imgur-embed-pub" lang="en" data-id="a/MbwHpmq"  ><a href="//imgur.com/a/MbwHpmq">Head Trip</a></blockquote>

**Comment by Beinabih** [comment]
Nice projects :)

I can implement the other architectures when i have time. 

I am not sure how to boost the speed. It depends on the image size, network structure and parameters. In most cases, visual pleasing results usually take longer since we need more octaves and iterations. Mixed precision makes it a bit faster but its not supported for every GPU.
